name: CI_CD_FrontEnd

on:
  push:
    branches: 
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Dependencies
      run: npm install

    - name: Build app
      run: npm run build
            
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # - name: Deploy to Azure
    #   uses: TravisSpomer/deploy-to-azure-storage@v1.5.0
    #   with:
    #     source-path: build
    #     sas-url: ${{ secrets.DEPLOY_SAS_URL }}

    - name: 'Build and push image'
       uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/learnon:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/learnon:${{ github.sha }}

  deployment:
      runs-on: ubuntu-latest
      needs: [ build ]
      steps:

      # Set the target AKS cluster.
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: Cluster
          resource-group: LearnOn
        
      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.ACR_USERNAME }}
          container-registry-password: ${{ secrets.ACR_PASSWORD }}
          secret-name: k8s-secret

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            ./manifests/frontend.yaml
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/learnon:${{ github.sha }}
          imagepullsecrets: |
            k8s-secret


